version: '3'
services:
  backend:
    build:
      context: ./rocketfy-test-CRV-backend
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
    networks:
      - mynetwork
    container_name: backend

  frontend:
    build:
      context: ./rocketfy-test-CRV-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mynetwork
    container_name: frontend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    container_name: mongodb

networks:
  mynetwork:
    driver: bridge
